#!/usr/bin/env bash


#sudo pacman -Sy xmonad xmonad-contrib dtos-xmonad xmobar dtos-xmobar polybar dtos-polybar
#sudo pacman -S dtos-polybar dtos-xmobar polybar xmobar
#cp /etc/dtos/.config/xmonad/xmonad-example-configs/xmonad-with-polybar.hs "$HOME"/.config/xmonad/xmonad.hs



sudo pacman -Sy --needed --noconfirm \
xmonad \
xmonad-contrib \
xmobar \
adapta-gtk-theme \
adobe-source-code-pro-fonts \
adobe-source-sans-fonts \
alacritty \
alsa-utils \
arandr \
arc-gtk-theme \
arc-icon-theme \
avahi \
base-devel \
bluez \
bluez-utils \
bash \
bat \
btop \
brave-bin \
cairo \
cbatticon \
chromium \
cmake \
copyq \
cups \
dmenu-distrotube \
dmscripts-git \
dtos-cache \
dtos-dmscripts \
dtos-local-bin \
dtos-rofi \
dtos-sxiv \
dtos-xresources \
dtos-xwallpaper \
dtos-zsh \
dunst \
elementary-icon-theme \
eza \
fd \
firefox \
fish \
fzf \
git \
gparted \
kvantum \
libxft \
libvterm \
lm_sensors \
lolcat \
lxappearance \
lxsession \
maim \
mpc \
mpd \
mpv \
neovim \
networkmanager \
network-manager-applet \
noto-fonts-cjk \
noto-fonts-emoji \
nvidia-dkms \
nvidia-utils \
nvidia-settings \
obs-studio \
octopi \
otf-raleway \
os-prober \
pacman-contrib \
pandoc \
paru-git \
pass \
pavucontrol \
pcmanfm-gtk3 \
picom \
pipewire \
polkit \
polkit-gnome \
qalculate-gtk \
rhythmbox \
ripgrep \
rofi \
shellcheck \
slock \
starship \
stack \
starship \
sxiv \
symlinks \
system-config-printer \
translate-shell \
timidity++ \
translate-shell \
trayer \
ttf-hack \
ttf-hack-nerd \
ttf-mononoki-nerd \
ttf-ms-fonts \
ttf-noto-nerd \
ttf-ubuntu-font-family \
ttf-ubuntu-nerd \
ttf-ubuntu-mono-nerd \
volumeicon \
vlc \
wget \
wildmidi \
xdg-desktop-portal \
xdg-desktop-portal-kde \
xdg-user-dirs \
xclip \
xdotool \
xf86-input-evdev \
xf86-input-libinput \
xf86-input-synaptics \
xf86-input-vmmouse \
xf86-input-void \
xf86-input-wacom \
xf86-video-amdgpu \
xf86-video-intel \
xf86-video-nouveau \
xf86-video-qxl \
xf86-video-vmware \
xl2tpd \
xorg-server \
xorg-xkill \
xorg-xmessage \
xorg-xprop \
xorg-xrdb \
xorg-xset \
xorg-xsetroot \
xterm \
xwallpaper \
yad \
yt-dlp \
zathura \
zathura-pdf-poppler \
zsh
