# Button order (optional)
button_order = ["cancel", "logout", "reboot", "shutdown", "lock", "suspend", "hibernate"]

# Programs to terminate before logout
programs_to_terminate = ["example_program1", "example_program2"]

# Custom lock screen application (optional)
lock_screen_app = "i3lock -c 313244"

# Window configuration
[window]
width = 788
height = 118
title = "nlogout"
background_color = "#33658a"

# Font configuration
[font]
family = "Noto Sans Mono"
size = 14
bold = true

# Global button configuration
[button]
show_text = true
keybind_text = true
width = 100
height = 100
padding = 3
top_padding = 3
corner_radius = 10 # Radius of 0 = square button
icon_size = 40
icon_theme = "sardi-tory"

# Individual button configurations
[buttons.cancel]
text = "Cancel"
background_color = "#d3c6aa"
text_color = "#2d353b"
shortcut = "Escape"

[buttons.logout]
text = "Logout"
background_color = "#d699b6"
text_color = "#2d353b"
shortcut = "L"

[buttons.reboot]
text = "Reboot"
background_color = "#e67e80"
text_color = "#2d353b"
shortcut = "R"

[buttons.shutdown]
text = "Shutdown"
background_color = "#e69875"
text_color = "#2d353b"
shortcut = "S"

[buttons.lock]
text = "Lock"
background_color = "#7fbbb3"
text_color = "#2d353b"
shortcut = "K"

[buttons.suspend]
text = "Suspend"
background_color = "#9da9a0"
text_color = "#2d353b"
shortcut = "U"

[buttons.hibernate]
text = "Hibernate"
background_color = "#83c092"
text_color = "#363a4f"
shortcut = "H"
